apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-oceancd-controller
  labels:
    app: spot-oceancd-controller
    {{- include "spot-oceancd-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spot-oceancd-operator
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: spot-oceancd-operator
        {{- include "spot-oceancd-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: spot-oceancd-controller
          imagePullPolicy: Always
          image: spotinst/spot-oceancd-controller:latest
          ports:
            - containerPort: 8000
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: spot-oceancd-controller-token
                  key: token
            - name: SAAS_URL
              valueFrom:
                secretKeyRef:
                  name: spot-oceancd-controller-token
                  key: saasUrl
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: spot-oceancd-operator-tls
              mountPath: /tls
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: spot-oceancd-operator-tls
          secret:
            secretName: spot-oceancd-operator-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
