apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: virtualnode
  namespace: mynamespace
spec:
  podSelector:
    matchLabels:
      app: nginx
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: my-service-a.my-apps.svc.cluster.local