
token: ""

saasUrl: https://operator.oceancd.io

apiUrl: https://api.spotinst.io

clusterId: ""

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
    
channel: "stable"
