{{- if .Values.argo-rollouts.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: spot-oceancd-operator
  name: argo-rollouts
  namespace: argo-rollouts
  {{- with .Values.argo-rollouts.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}