apiVersion: batch/v1
kind: Job
metadata:
  name: spot-oceancd-controller-installer
  labels:
    app: spot-oceancd-controller-installer
    {{- include "spot-oceancd-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: spot-oceancd-controller-installer-service-account
      containers:
        - name: spot-oceancd-controller-installer
          image: spotinst/spot-oceancd-controller-installer:helm
          imagePullPolicy: Always
          command: ["./installation.sh"]
          args:
            - "--service"
            - "spot-oceancd-controller-svc"
            - "--webhook"
            - "controller.oceancd.spot.io"
            - "--secret"
            - "spot-oceancd-controller-tls"
            - "--namespace"
            - {{ .Release.Namespace }}
            - "--token"
            - {{ .Values.token }}
            - "--apiurl"
            - {{ .Values.apiUrl }}
            - "--clusterId"
            - {{ .Values.clusterId }}
            - "--saasurl"
            - {{ .Values.saasUrl }}
      restartPolicy: Never
  backoffLimit: 1