apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "controller.oceancd.spot.io"
webhooks:
  - name: "controller.oceancd.spot.io"
    failurePolicy: Ignore
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: "spot-oceancd-controller-svc"
        path: "/mutate"
        port: 8000
      caBundle: ""
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: NoneOnDryRun
    timeoutSeconds: 5
    reinvocationPolicy: Never