apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spot-oceancd-operator-subscription
  namespace: oceancd
spec:
  channel: ga
  name: spot-oceancd-operator
  source: spot-oceancd-catalog
  sourceNamespace: oceancd